# Generated by Django 3.2.8 on 2021-11-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LsS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(default='media/ProfilePics/', upload_to='ProfilePics'),
        ),
    ]
