# Generated by Django 3.2.8 on 2021-11-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LsS', '0002_profilemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(default='media/ProfilePics/thumb_15951118880user.png', upload_to='ProfilePics'),
        ),
    ]
